imx: fix errors when CONFIG_SOC_IMX6SLL is not defined
I'm not exactly sure how to properly fix the cpuidle part as the whole file seems to assume all IMX* are enabled
so this is mostly a "bug-report" instead of a proper patch

arch/arm/mach-imx/built-in.o: In function `init_mmdc_lpddr2_settings':
platform-imx-dma.c:(.text+0x9938): undefined reference to `imx6sll_lpddr2_freq_change'
platform-imx-dma.c:(.text+0x993c): undefined reference to `imx6sll_lpddr2_freq_change'
arch/arm/mach-imx/built-in.o: In function `imx6sl_init_late':
platform-imx-dma.c:(.init.text+0xdef0): undefined reference to `imx6sll_cpuidle_init'

Signed-off-by: Alejandro Mery <amery@hanoverdisplays.com>