zram-remove-bd_cap_synchronous_io-with-writeback-feature-v2-checkpatch-fixes
ERROR: code indent should use tabs where possible
#28: FILE: drivers/block/zram/zram_drv.c:405:
+ ^I * With writeback feature, zram does asynchronous IO so it's no longer$

WARNING: please, no space before tabs
#28: FILE: drivers/block/zram/zram_drv.c:405:
+ ^I * With writeback feature, zram does asynchronous IO so it's no longer$

ERROR: code indent should use tabs where possible
#29: FILE: drivers/block/zram/zram_drv.c:406:
+ ^I * synchronous device so let's remove synchronous io flag. Othewise,$

WARNING: please, no space before tabs
#29: FILE: drivers/block/zram/zram_drv.c:406:
+ ^I * synchronous device so let's remove synchronous io flag. Othewise,$

ERROR: code indent should use tabs where possible
#32: FILE: drivers/block/zram/zram_drv.c:409:
+ ^I * Furthermore, when the IO function returns(e.g., swap_readpage),$

WARNING: please, no space before tabs
#32: FILE: drivers/block/zram/zram_drv.c:409:
+ ^I * Furthermore, when the IO function returns(e.g., swap_readpage),$

ERROR: code indent should use tabs where possible
#33: FILE: drivers/block/zram/zram_drv.c:410:
+ ^I * upper layer expects IO was done so it could deallocate the page$

WARNING: please, no space before tabs
#33: FILE: drivers/block/zram/zram_drv.c:410:
+ ^I * upper layer expects IO was done so it could deallocate the page$

ERROR: code indent should use tabs where possible
#34: FILE: drivers/block/zram/zram_drv.c:411:
+ ^I * freely but in fact, IO is going on so finally could cause$

WARNING: please, no space before tabs
#34: FILE: drivers/block/zram/zram_drv.c:411:
+ ^I * freely but in fact, IO is going on so finally could cause$

ERROR: code indent should use tabs where possible
#35: FILE: drivers/block/zram/zram_drv.c:412:
+ ^I * use-after-free when the IO is really done.$

WARNING: please, no space before tabs
#35: FILE: drivers/block/zram/zram_drv.c:412:
+ ^I * use-after-free when the IO is really done.$

ERROR: code indent should use tabs where possible
#36: FILE: drivers/block/zram/zram_drv.c:413:
+ ^I */$

WARNING: please, no space before tabs
#36: FILE: drivers/block/zram/zram_drv.c:413:
+ ^I */$

total: 7 errors, 7 warnings, 16 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/zram-remove-bd_cap_synchronous_io-with-writeback-feature-v2.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Minchan Kim <minchan@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>