Revert "cpufreq: imx7: fix undefined reference to arm_reg and soc_reg"
This reverts commit a6563bd605a42e5a54c19b1588457d687651d9c1.

The fix provided creates issues if the kernel is configured to
be built for both i.MX 6 and i.MX 7 devices.

Revert in favor of a more universal fix.

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
Acked-by: Dominik Sliwa <dominik.sliwa@toradex.com>