arm: tegra: ardbeg: fix gcc-6 compilation
arch/arm/mach-tegra/board-ardbeg.c: In function 'ardbeg_touch_init':
arch/arm/mach-tegra/board-ardbeg.c:1159:6: error: this 'else' clause
does not guard... [-Werror=misleading-indentation]
    } else
      ^~~~
arch/arm/mach-tegra/board-ardbeg.c:1161:5: note: ...this statement, but
the latter is misleadingly indented as if it is guarded by the 'else'
     rm31080a_ardbeg_spi_board[0].irq =
     ^~~~~~~~~~~~~~~~~~~~~~~~~
arch/arm/mach-tegra/board-ardbeg.c: In function 'tegra_ardbeg_late_init':
arch/arm/mach-tegra/board-ardbeg.c:1470:2: error: this 'else' clause
does not guard... [-Werror=misleading-indentation]
  else
  ^~~~
arch/arm/mach-tegra/board-ardbeg.c:1474:3: note: ...this statement, but
the latter is misleadingly indented as if it is guarded by the 'else'
   tegra_io_dpd_enable(&pexbias_io);
   ^~~~~~~~~~~~~~~~~~~
At top level:
arch/arm/mach-tegra/board-ardbeg.c:1608:27: error:
'loki_dt_board_compat' defined but not used
[-Werror=unused-const-variable=]
 static const char * const loki_dt_board_compat[] = {
                           ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Max Krummenacher <max.krummenacher@toradex.com>