of: irq: export symbol of_irq_count()
A kernel built with CONFIG_OF_IRQ usually fails to link because of unreachable
function of_irq_count(). I.e.:

    ERROR: "of_irq_count" [drivers/dma/fsl-edma.ko] undefined!
    make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1

This change fixes such kind linking errors.

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>