tegra: fix usb_phy build breakage if gadget as module
Add missing symbol exports to address gcc 4.7.1 from oe-core throwing following errors if usb gadget stuff compiled as modules:

ERROR: "tegra_usb_phy_memory_prefetch_on" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_memory_prefetch_off" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_charger_detect" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_power_off" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_close" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_power_on" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!
ERROR: "tegra_usb_phy_open" [drivers/usb/gadget/fsl_usb2_udc.ko] undefined!

While at it following build time warning addressed as well:

arch/arm/mach-tegra/usb_phy.c: In function 'utmi_phy_postresume':
arch/arm/mach-tegra/usb_phy.c:1678:16: warning: unused variable 'inst' [-Wunused-variable]