media: vidc: fix compile error
It seem that it occurs when kernel is built without using
O=/kobj/path option. That explains why I hadn't reproduced
while trying cause I always used kobj directory in my
builds.

fix the following compile error:

CHK     include/config/kernel.release
   CHK     include/generated/uapi/linux/version.h
   CHK     include/generated/utsrelease.h
   CHK     include/generated/bounds.h
   CHK     include/generated/timeconst.h
   CHK     include/generated/asm-offsets.h
   CALL    scripts/checksyscalls.sh
   CHK     include/generated/compile.h
   CHK     kernel/config_data.h
   CC      drivers/media/platform/msm/vidc/msm_v4l2_vidc.o
In file included from drivers/media/platform/msm/vidc/msm_vidc_internal.h:33:0,
                  from drivers/media/platform/msm/vidc/msm_vidc_common.h:19,
                  from drivers/media/platform/msm/vidc/msm_v4l2_vidc.c:25:
drivers/media/platform/msm/vidc/hfi/vidc_hfi_api.h:21:22: fatal error: msm_vidc.h: No such file or directory
  #include "msm_vidc.h"
                       ^
compilation terminated.
make[5]: *** [drivers/media/platform/msm/vidc/msm_v4l2_vidc.o] Error 1
make[4]: *** [drivers/media/platform/msm/vidc] Error 2
make[3]: *** [drivers/media/platform/msm] Error 2
make[2]: *** [drivers/media/platform] Error 2
make[1]: *** [drivers/media] Error 2
make: *** [drivers] Error 2

Signed-off-by: Stanimir Varbanov <stanimir.varbanov@linaro.org>