video: tegra: dc: fix size optimised nvhdcp build using gcc 4.7.2
With our default gcc 4.7.2 toolchain from oe building nvhdcp with
activated CONFIG_CC_OPTIMIZE_FOR_SIZE fails as follows:

/linux-toradex.git/drivers/video/tegra/dc/nvhdcp.c: In function
'nvhdcp_downstream_worker':
/linux-toradex.git/drivers/video/tegra/dc/nvhdcp.c:807:3: error:
'b_status' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
/linux-toradex.git/drivers/video/tegra/dc/nvhdcp.c:763:6: note:
'b_status' was declared here
make[5]: *** [drivers/video/tegra/dc/nvhdcp.o] Error 1