apalis_t30: fix build without SATA support
This patch fixes building without CONFIG_SATA_AHCI_TEGRA aka SATA
support which previously failed as follows:

...
  CC      arch/arm/mach-tegra/board-apalis_t30.o
~/linux-toradex/arch/arm/mach-tegra/board-apalis_t30.c:571:31: error:
'apalis_led_gpio_device' defined but not used [-Werror=unused-variable]
cc1: all warnings being treated as errors
make[2]: *** [arch/arm/mach-tegra/board-apalis_t30.o] Error 1
make[1]: *** [arch/arm/mach-tegra] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [sub-make] Error 2