net: sch_generic: fix compiling
This fixes the following error upon compiling:

/fslc/4.14-2.3.x-imx/net/sched/sch_generic.c: In function ‘attach_one_default_qdisc’:
/fslc/4.14-2.3.x-imx/net/sched/sch_generic.c:771:23: error: ‘ARPHRD_CAN’ undeclared (first use in this function); did you mean ‘ETH_P_CAN’?
  else if(dev->type == ARPHRD_CAN)
                       ^~~~~~~~~~
                       ETH_P_CAN
/fslc/4.14-2.3.x-imx/net/sched/sch_generic.c:771:23: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [/fslc/4.14-2.3.x-imx/scripts/Makefile.build:326: net/sched/sch_generic.o] Error 1
make[2]: *** [/fslc/4.14-2.3.x-imx/scripts/Makefile.build:585: net/sched] Error 2
make[2]: *** Waiting for unfinished jobs....

Fixes: fb1d29ab844c ("net: sch_generic: Use pfifo_fast as fallback scheduler for CAN hardware")
Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>