[4.2-stable only] Revert "perf test: Ignore kcore files in the "vmlinux matches kallsyms" test"
BugLink: http://bugs.launchpad.net/bugs/1592552

This reverts commit 159436d273a248e99f05dcd15f39e2c6bdb02652.

Causes an FTBS.

tests/vmlinux-kallsyms.c: In function 'test__vmlinux_matches_kallsyms':
tests/vmlinux-kallsyms.c:64:6: error: implicit declaration of function '__machine__load_kallsyms' [-Werror=implicit-function-declaration]
  if (__machine__load_kallsyms(&kallsyms, "/proc/kallsyms", type, true, NULL) <= 0) {
      ^
tests/vmlinux-kallsyms.c:64:2: error: nested extern declaration of '__machine__load_kallsyms' [-Werror=nested-externs]
  if (__machine__load_kallsyms(&kallsyms, "/proc/kallsyms", type, true, NULL) <= 0) {
  ^
cc1: all warnings being treated as errors

Signed-off-by: Tim Gardner <tim.gardner@canonical.com>
Signed-off-by: Kamal Mostafa <kamal@canonical.com>