usb: chipidea: Fix enum name conflict
This fixes a compilation error:

 CC      drivers/rtc/rtc-lib.o
In file included from drivers/phy/ti/phy-omap-usb2.c:30:0:
./include/linux/phy/omap_control_phy.h:46:2: error: redeclaration of enumerator ‘USB_MODE_HOST’
  USB_MODE_HOST,
  ^~~~~~~~~~~~~
In file included from ./include/linux/usb/otg.h:14:0,
                 from ./include/linux/phy/omap_usb.h:23,
                 from drivers/phy/ti/phy-omap-usb2.c:24:
./include/linux/usb/phy.h:69:2: note: previous definition of ‘USB_MODE_HOST’ was here
  USB_MODE_HOST,
  ^~~~~~~~~~~~~
In file included from drivers/phy/ti/phy-omap-usb2.c:30:0:
./include/linux/phy/omap_control_phy.h:47:2: error: redeclaration of enumerator ‘USB_MODE_DEVICE’
  USB_MODE_DEVICE,
  ^~~~~~~~~~~~~~~
In file included from ./include/linux/usb/otg.h:14:0,
                 from ./include/linux/phy/omap_usb.h:23,
                 from drivers/phy/ti/phy-omap-usb2.c:24:
./include/linux/usb/phy.h:70:2: note: previous definition of ‘USB_MODE_DEVICE’ was here
  USB_MODE_DEVICE,
  ^~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:328: drivers/phy/ti/phy-omap-usb2.o] Error 1
  AR      drivers/pps/clients/built-in.o
make[2]: *** [scripts/Makefile.build:587: drivers/phy/ti] Error 2
make[1]: *** [scripts/Makefile.build:587: drivers/phy] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      drivers/rtc/hctosys.o

Related to: #50570
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>