tegra: pcie: fix build
Fix the following build error using our OpenEmbedded gcc-4.7:

arch/arm/mach-tegra/pcie.c:335:22: error: 'reg_pmc_base' defined but
not used [-Werror=unused-variable]
cc1: all warnings being treated as errors