mxc_v4l2_capture: Change error message to print on debug
Change the "unsupported ioctrl" message to print only on debug.
This otherwise results in an error message

ERROR: v4l2 capture: unsupported ioctrl!

which does not seem to effect the gstreamer pipeline or rendering
of video.

>From debugging,

root@apalis-imx6:~# gst-launch-1.0 imxv4l2videosrc ! imxeglvivsink
Setting pipeline to PAUSED ...
[  385.174543] ERROR: v4l2 capture: unsupported ioctrl 9a091b!
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock

>From v4l2-controls.h

V4L2_CTRL_CLASS_CAMERA          0x009a0000
V4L2_CID_CAMERA_CLASS_BASE      V4L2_CTRL_CLASS_CAMERA | 0x900
V4L2_CID_3A_LOCK                V4L2_CID_CAMERA_CLASS_BASE + 27

So the ioctrl requested seems to be V4L2_CID_3A_LOCK.

"The V4L2_CID_3A_LOCK bitmask control allows applications to pause
or resume the automatic exposure, focus and wite balance adjustments.
It can be used, for example, to lock the 3A adjustments right before
a still image is captured, for pre-focus, etc.
The applications can control each of the algorithms independently,
through a corresponding control bit, if driver allows that."
https://patchwork.linuxtv.org/patch/10719/

Since we have no such feature available we can safely disable the
error message.

Signed-off-by: Sanchayan Maity <sanchayan.maity@toradex.com>
Acked-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
(cherry picked from commit f1b52e225091711d60704717af34c2f321c032b3)
(cherry picked from commit 358a46afbf83035dc02d7b017088d5644ef9a74e)