colibri_t20: fix gcc-6 compilation
arch/arm/mach-tegra/board-colibri_t20.c:668:43: error: 'i2c2_ddc'
defined but not used [-Werror=unused-const-variable=]
 static const struct tegra_pingroup_config i2c2_ddc = {
                                           ^~~~~~~~

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Max Krummenacher <max.krummenacher@toradex.com>