mxc: hantro: Kconfig: add COMPAT dependancy
Building hantro_845_h1 with undefined CONFIG_COMPAT leads to
compillation error:

drivers/mxc/hantro_845_h1/hx280enc.c: In function ‘hx280enc_ioctl32’:
drivers/mxc/hantro_845_h1/hx280enc.c:460:23: error: implicit declaration of function ‘compat_ptr’; did you mean ‘compat_lr’? [-Werror=implicit-function-declaration]
     void __user *up = compat_ptr(arg);
                       ^~~~~~~~~~
                       compat_lr

This driver uses compat_ptr() so requires CONFIG_COMPAT to be selected.

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>