Compiler Attributes: Fix: add support for __copy (gcc >= 9)
For not gcc >= 9 compilers the fix for gcc9 introduced compiler errors.

| ./include/linux/module.h:131:6: error: ‘init_module’ declared as function returning a function
|  int init_module(void) __copy(initfn) __attribute__((alias(#initfn)));

Fixes backport 865ca1d1e

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>