tegra: dc: events.c: fix error about unknown pragma
Fixes: '3f76b6ebb8c tegra: dc: events.c: fix error about packed' if
GCC < 9.0.1 is used.

| events.c:195:32: error: unknown option after '#pragma GCC diagnostic' kind [-Werror=pragmas]
|  #pragma GCC diagnostic warning "-Waddress-of-packed-member"
|                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>