colibri_t30: MMC: fix building for SDMMC4B
This fixes the following build issue:

arch/arm/mach-tegra/board-colibri_t30.c:276:41: error:
'colibri_t30_emmc_platform_data' defined but not used
[-Werror=unused-variable]
cc1: all warnings being treated as errors