Revert "cpufreq: imx7: fix undefined reference to arm_reg and soc_reg"
This reverts commit a6563bd605a42e5a54c19b1588457d687651d9c1.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>