video: tegra: dc: fix gcc-6 compilation
drivers/video/tegra/dc/dc.c:116:3: error: 'can_filter' defined but not
used [-Werror=unused-const-variable=]
 } can_filter[] = {
   ^~~~~~~~~~

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Max Krummenacher <max.krummenacher@toradex.com>