colibri_t20: mmc: sdhci: fix build
Fix the following build issue introduced by commit
5cfcbc23d116927a7ae8d5b67baeacf2905b21f9 if neither
CONFIG_MACH_APALIS_T30 nor CONFIG_MACH_COLIBRI_T30 is defined as in
case of e.g. the Colibri T20:

drivers/mmc/host/sdhci-tegra.c:951:2:
 error: expected expression before '.' token