colibri_t20: USB: fix building device controller driver as module
Trying to build USB device controller driver as a module failed as
follows:

ERROR: "g_usb_high_speed" [drivers/usb/gadget/tegra_udc.ko] undefined!

This is due to a missing export of above mentioned global variable.